---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: java-centos6-11-jdk
    image: centos
    image_version: 6.8
    groups:
      - jdk

  - name: java-centos7-11-jdk
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - jdk

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      jdk:
        java_type: 'jdk'
      server-jre:
        java_type: 'serverjre'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
